<?php

namespace App\Filament\Resources\Scripts;

use App\Filament\Resources\Scripts\Pages\ListScripts;
use App\Filament\Resources\Scripts\Pages\ViewScript;
use App\Filament\Resources\Scripts\Schemas\ScriptInfolist;
use App\Filament\Resources\Scripts\Tables\ScriptsTable;
use App\Models\Script;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Table;
use UnitEnum;

class ScriptResource extends Resource
{
    protected static ?string $model = Script::class;

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedCodeBracket;

    protected static string|UnitEnum|null $navigationGroup = 'AI';

    protected static ?int $navigationSort = 2;

    protected static ?string $recordTitleAttribute = 'title';

    public static function infolist(Schema $schema): Schema
    {
        return ScriptInfolist::configure($schema);
    }

    public static function table(Table $table): Table
    {
        return ScriptsTable::configure($table);
    }

    public static function getRelations(): array
    {
        return [];
    }

    public static function getPages(): array
    {
        // Scripts are requested via the public API and generated by the worker;
        // the admin panel is for audit/review only.
        return [
            'index' => ListScripts::route('/'),
            'view' => ViewScript::route('/{record}'),
        ];
    }

    public static function canCreate(): bool
    {
        return false;
    }
}
