<?php

declare(strict_types=1);

namespace App\Http\Controllers\Internal;

use App\Http\Controllers\Controller;
use App\Http\Requests\Internal\StoreSiteBriefRequest;
use App\Http\Resources\SiteBriefResource;
use App\Models\Site;
use App\Support\CurrentTenant;

/**
 * Internal endpoint: persist an AI Site Brief generated by the worker.
 *
 * Called over the HMAC channel (no user session). The site is resolved without
 * the tenant global scope; the tenant is set from the site so the brief is
 * stored against the correct tenant (the BelongsToTenant trait stamps
 * tenant_id on create).
 */
class StoreSiteBriefController extends Controller
{
    public function __invoke(StoreSiteBriefRequest $request, int $siteId): SiteBriefResource
    {
        $site = Site::withoutGlobalScopes()->findOrFail($siteId);
        CurrentTenant::set($site->tenant_id);

        $brief = $site->briefs()->create($request->validated());

        return SiteBriefResource::make($brief);
    }
}
